name: app
description: A template for flutter app with UaaL.
publish_to: 'none'
version: 1.1.0+0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_unity_widget:
    git:
      url: git@github.com:timbotimbo/flutter-unity-view-widget.git
      ref: android_java_proxy_2

  protobuf: ^3.1.0

  # For Architecture
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.3.6

  # For model
  freezed_annotation: ^2.2.0

  # UI
  cupertino_icons: ^1.0.2
  auto_route: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.3.4
  build_runner: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  auto_route_generator: any
  flutter_lints:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
