name: app
description: A template for flutter app with UaaL.
publish_to: 'none'
version: 1.1.0+0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^9.2.2
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.20.5
  flutter_unity_widget: ^2022.2.1
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.6.1
  protobuf: ^3.1.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  freezed: ^2.3.4
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
